export {
  createSingleton,
  defineSingleton,
  createTransient,
  defineTransient,
  createScoped,
  defineScoped,
  defineAppTeardown,
  type ContextualScopedOptions,
  type DiOptions,
  type ReleasableScopedOptions,
  type ScopedAccessor,
  type ScopedController,
  type ScopedLifecycle,
  type ScopedProxy,
  type ScopedReleaseHandler,
  type ScopedReleaseResult,
} from "@compdi/core";
