// Generated by Compdi
// Style: interfaces with dispose symbols, no generics on macro calls (inferred)
interface IDatabase {
  query(sql: string): Promise<unknown>;
  [Symbol.dispose](): void;
}

interface ICacheClient {
  get(key: string): unknown;
  [Symbol.dispose](): void;
}

interface IConnection {
  [Symbol.asyncDispose](): Promise<void>;
}

class Database implements IDatabase {
  async query(sql: string): Promise<unknown> { return sql; }
  [Symbol.dispose]() {}
}

class CacheClient implements ICacheClient {
  get(key: string) { return key; }
  [Symbol.dispose]() {}
}

async function openConnection(): Promise<IConnection> {
  return {
    async [Symbol.asyncDispose]() {}
  };
}

export const db = new Database();
const __useConnection: ReturnType<typeof openConnection> = (openConnection)();
export const useConnection = () => __useConnection;
let __lazy_useCacheClient: CacheClient | null = null;
const __peek_useCacheClient = () => __lazy_useCacheClient;
export const useCacheClient = () => {
  if (!__lazy_useCacheClient) __lazy_useCacheClient = new CacheClient();
  return __lazy_useCacheClient;
};
export const teardown = async () => {
  const tasks = [];
  const __resource_0 = db;
  if (__resource_0 != null && Symbol.asyncDispose in __resource_0) {
    // @ts-ignore
    tasks.push(__resource_0[Symbol.asyncDispose]());
  } else if (__resource_0 != null && Symbol.dispose in __resource_0) {
    try {
      // @ts-ignore
      __resource_0[Symbol.dispose]();
    } catch (error) {
      tasks.push(Promise.reject(error));
    }
  }
  const __resource_1 = __useConnection;
  if (__resource_1 != null && Symbol.asyncDispose in __resource_1) {
    // @ts-ignore
    tasks.push(__resource_1[Symbol.asyncDispose]());
  } else if (__resource_1 != null && Symbol.dispose in __resource_1) {
    try {
      // @ts-ignore
      __resource_1[Symbol.dispose]();
    } catch (error) {
      tasks.push(Promise.reject(error));
    }
  }
  const __resource_2 = __peek_useCacheClient();
  if (__resource_2 != null && Symbol.asyncDispose in __resource_2) {
    // @ts-ignore
    tasks.push(__resource_2[Symbol.asyncDispose]());
  } else if (__resource_2 != null && Symbol.dispose in __resource_2) {
    try {
      // @ts-ignore
      __resource_2[Symbol.dispose]();
    } catch (error) {
      tasks.push(Promise.reject(error));
    }
  }
  await Promise.allSettled(tasks);
};
