import MagicString from "magic-string";
import { parseSync } from "oxc-parser";
import {
  findMatchingParen,
  resolveDependencies,
  splitDependencyList,
  splitTopLevelArgs
} from "@compdi/shared";

type Replacement = {
  start: number;
  end: number;
  code: string;
};

const CORE_IMPORT_REGEX = /import\s*{[^}]*}\s*from\s*["']@compdi\/core["'];?\s*/g;
const SINGLETON_REGEX =
  /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineSingleton\(\s*([\s\S]*?),\s*\[([\s\S]*?)\]\s*\)\s*;?/g;
const TRANSIENT_REGEX =
  /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineTransient\(\s*([\s\S]*?),\s*\[([\s\S]*?)\]\s*\)\s*;?/g;
const LAZY_REGEX =
  /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineLazySingleton\(\s*([\s\S]*?),\s*\[([\s\S]*?)\]\s*\)\s*;?/g;
const TEARDOWN_REGEX =
  /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineAppTeardown\(\s*\[([\s\S]*?)\]\s*\)\s*;?/g;

function parseWithOxc(code: string, id: string): boolean {
  try {
    parseSync(id, code, { showSemanticErrors: false });
    return true;
  } catch {
    return false;
  }
}

function findSingletonBindings(code: string): Set<string> {
  const bindings = new Set<string>();

  for (const match of code.matchAll(SINGLETON_REGEX)) {
    const name = match[1];
    bindings.add(name);
  }

  return bindings;
}

function collectAsyncSingletonReplacements(
  code: string,
  singletonBindings: ReadonlySet<string>
): Replacement[] {
  const replacements: Replacement[] = [];
  const headRegex =
    /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineAsyncSingleton\s*\(/g;

  let headMatch = headRegex.exec(code);
  while (headMatch) {
    const name = headMatch[1];
    const openParenIndex = headRegex.lastIndex - 1;
    const closeParenIndex = findMatchingParen(code, openParenIndex);

    if (closeParenIndex < 0) {
      headMatch = headRegex.exec(code);
      continue;
    }

    let endIndex = closeParenIndex + 1;
    while (endIndex < code.length && /\s/.test(code[endIndex])) {
      endIndex += 1;
    }
    if (code[endIndex] === ";") {
      endIndex += 1;
    }

    const argsSource = code.slice(openParenIndex + 1, closeParenIndex);
    const args = splitTopLevelArgs(argsSource);
    if (!args) {
      headMatch = headRegex.exec(code);
      continue;
    }

    const [factory, depsExpr] = args;
    const depsMatch = depsExpr.match(/^\[([\s\S]*)\]$/);
    const rawDeps = depsMatch ? depsMatch[1] : "";
    const deps = resolveDependencies(rawDeps, singletonBindings);

    const invokeArgs = deps.trim() ? deps : "";
    replacements.push({
      start: headMatch.index,
      end: endIndex,
      code: `const __${name} = await (${factory})(${invokeArgs});\nexport const ${name} = __${name};`
    });

    headRegex.lastIndex = endIndex;
    headMatch = headRegex.exec(code);
  }

  return replacements;
}

function applyReplacements(code: string, replacements: Replacement[]): string {
  if (replacements.length === 0) {
    return code;
  }

  const ms = new MagicString(code);
  const sorted = [...replacements].sort((left, right) => right.start - left.start);

  for (const replacement of sorted) {
    ms.overwrite(replacement.start, replacement.end, replacement.code);
  }

  ms.prepend("// Generated by Compdi\n");
  return ms.toString();
}

export function transformCompdiMacros(code: string, id: string): string | null {
  if (!/\.[cm]?[jt]sx?$/.test(id)) {
    return null;
  }

  if (!code.includes("@compdi/core")) {
    return null;
  }

  if (!parseWithOxc(code, id)) {
    return null;
  }

  const singletonBindings = findSingletonBindings(code);
  const replacements: Replacement[] = [];

  for (const match of code.matchAll(CORE_IMPORT_REGEX)) {
    replacements.push({
      start: match.index ?? 0,
      end: (match.index ?? 0) + match[0].length,
      code: ""
    });
  }

  for (const match of code.matchAll(SINGLETON_REGEX)) {
    const name = match[1];
    const target = match[2].trim();
    const deps = resolveDependencies(match[3], singletonBindings);
    replacements.push({
      start: match.index ?? 0,
      end: (match.index ?? 0) + match[0].length,
      code: `const __${name} = new ${target}(${deps});\nexport const ${name} = __${name};`
    });
  }

  for (const match of code.matchAll(TRANSIENT_REGEX)) {
    const name = match[1];
    const target = match[2].trim();
    const deps = resolveDependencies(match[3], singletonBindings);
    replacements.push({
      start: match.index ?? 0,
      end: (match.index ?? 0) + match[0].length,
      code: `export const ${name} = () => new ${target}(${deps});`
    });
  }

  for (const match of code.matchAll(LAZY_REGEX)) {
    const name = match[1];
    const target = match[2].trim();
    const deps = resolveDependencies(match[3], singletonBindings);
    replacements.push({
      start: match.index ?? 0,
      end: (match.index ?? 0) + match[0].length,
      code: [
        `let __lazy_${name} = null;`,
        `export const ${name} = new Proxy({}, {`,
        `  get: (_, prop) => {`,
        `    if (!__lazy_${name}) __lazy_${name} = new ${target}(${deps});`,
        `    return Reflect.get(__lazy_${name}, prop);`,
        `  }`,
        `});`
      ].join("\n")
    });
  }

  for (const match of code.matchAll(TEARDOWN_REGEX)) {
    const name = match[1];
    const resources = splitDependencyList(match[2]).map((resource) =>
      singletonBindings.has(resource) ? `__${resource}` : resource
    );

    const lines = resources.flatMap((resource) => [
      `  if (${resource}?.[Symbol.asyncDispose]) tasks.push(${resource}[Symbol.asyncDispose]());`,
      `  else if (${resource}?.[Symbol.dispose]) {`,
      `    try {`,
      `      ${resource}[Symbol.dispose]();`,
      `    } catch (error) {`,
      `      tasks.push(Promise.reject(error));`,
      `    }`,
      `  }`
    ]);

    replacements.push({
      start: match.index ?? 0,
      end: (match.index ?? 0) + match[0].length,
      code: [
        `export const ${name} = async () => {`,
        `  const tasks = [];`,
        ...lines,
        `  await Promise.allSettled(tasks);`,
        `};`
      ].join("\n")
    });
  }

  replacements.push(...collectAsyncSingletonReplacements(code, singletonBindings));

  if (replacements.length === 0) {
    return null;
  }

  return applyReplacements(code, replacements);
}
