// Generated by Compdi
// Style: interfaces + explicit generics on all calls
interface IConfig {
  env: string;
  debug: boolean;
}

interface ILogger {
  log(msg: string): void;
}

interface IDatabase {
  query(sql: string): Promise<unknown>;
}

class Config implements IConfig {
  constructor(readonly env: string, readonly debug: boolean) {}
}

class Logger implements ILogger {
  constructor(readonly config: IConfig) {}
  log(msg: string) { console.log(msg); }
}

class Database implements IDatabase {
  constructor(readonly config: IConfig, readonly logger: ILogger) {}
  async query(sql: string): Promise<unknown> { return sql; }
}

export const config = new Config("production", false);
export const logger = new Logger(config);
export const db = new Database(config, logger);
