// Generated by Compdi
// Style: plain classes, no interfaces, no explicit generics (fully inferred)
class Config {
  constructor(readonly dsn: string) {}
}

function createCache(config: Config, ttl: number) {
  return { dsn: config.dsn, ttl };
}

export const config = new Config("redis://localhost");
export const cache = (createCache)(config, 300);
