// Generated by Compdi
// Style: explicit generic only on the awaited call, dependency inferred
interface IDatabase {
  url: string;
}

class SecretManager {
  async getSecret(name: string) {
    return `secret:${name}`;
  }
}

async function createDatabase(sm: SecretManager): Promise<IDatabase> {
  const url = await sm.getSecret("db-url");
  return { url };
}

export const secretManager = new SecretManager();
export const db = await (createDatabase)(secretManager);
