// Generated by Compdi
// Style: type aliases, explicit generic only on defineSingleton (the factory return)
type AppConfig = { dsn: string };
type AppLogger = { log(msg: string): void };
type DbConnection = { dsn: string; connected: boolean };

class Config {
  constructor(readonly dsn: string) {}
}

class Logger {
  constructor(readonly config: AppConfig) {}
  log(msg: string) { console.log(msg); }
}

async function openConnection(config: AppConfig, logger: AppLogger): Promise<DbConnection> {
  return { dsn: config.dsn, connected: true };
}

export const config = new Config("postgres://localhost/app");
export const logger = new Logger(config);
const __useConnection: ReturnType<typeof openConnection> = (openConnection)(config, logger);
export const useConnection = () => __useConnection;
