// Generated by Compdi
// Style: plain classes, explicit generics only on lazy defines
class Config {
  constructor(readonly env: string) {}
}

class Logger {
  constructor(readonly config: Config) {}
  log(msg: string) { console.log(msg); }
}

class HeavyAnalytics {
  constructor(readonly logger: Logger) {}
  track(event: string) { this.logger.log(event); }
}

class MetricsCollector {
  constructor(readonly analytics: HeavyAnalytics) {}
  record(metric: string, value: number) { this.analytics.track(`${metric}:${value}`); }
}

export const config = new Config("production");
export const logger = new Logger(config);
let __lazy_useAnalytics: HeavyAnalytics | null = null;
const __peek_useAnalytics = () => __lazy_useAnalytics;
export const useAnalytics = () => {
  if (!__lazy_useAnalytics) __lazy_useAnalytics = new HeavyAnalytics(logger);
  return __lazy_useAnalytics;
};
let __lazy_useMetrics: MetricsCollector | null = null;
const __peek_useMetrics = () => __lazy_useMetrics;
export const useMetrics = () => {
  if (!__lazy_useMetrics) __lazy_useMetrics = new MetricsCollector(useAnalytics());
  return __lazy_useMetrics;
};
