// Generated by Compdi
// Style: interfaces on classes, no explicit generics (inferred from target)
interface IConfig {
  env: string;
}

interface ILogger {
  log(msg: string): void;
}

interface IUserRepository {
  findById(id: string): unknown;
}

interface IUserService {
  getUser(id: string): unknown;
}

class Config implements IConfig {
  constructor(readonly env: string) {}
}

class Logger implements ILogger {
  constructor(readonly config: IConfig) {}
  log(msg: string) { console.log(msg); }
}

class UserRepository implements IUserRepository {
  constructor(readonly config: IConfig, readonly logger: ILogger) {}
  findById(id: string) { return { id }; }
}

class UserService implements IUserService {
  constructor(readonly repo: IUserRepository, readonly logger: ILogger) {}
  getUser(id: string) { return this.repo.findById(id); }
}

export const config = new Config("production");
export const logger = new Logger(config);
export const userRepo = new UserRepository(config, logger);
const __useUserService: UserService = new UserService(userRepo, logger);
export const useUserService = () => __useUserService;
