// Generated by Compdi
interface RequestContext {
  id: string;
}

interface Database {
  query(sql: string): unknown;
  close(): Promise<void>;
}

declare const useRequest: () => RequestContext;
declare const connectionString: string;
declare const createDatabase: (context: RequestContext, connectionString: string) => Database;

const __getContext_database = useRequest;
const __createScoped_database = (__context: ReturnType<typeof __getContext_database>) => (createDatabase)(__context, connectionString);
const __registry_database = new Map<ReturnType<typeof __getContext_database>, ReturnType<typeof __createScoped_database>>();
const __resolveScoped_database = () => {
  const __context = __getContext_database();
  if (__registry_database.has(__context)) return __registry_database.get(__context)!;
  const __instance = __createScoped_database(__context);
  __registry_database.set(__context, __instance);
  return __instance;
};
const __controller_database = {
  has: (__context: ReturnType<typeof __getContext_database>) => __registry_database.has(__context),
  peek: (__context: ReturnType<typeof __getContext_database>) => __registry_database.get(__context),
  release: (__context: ReturnType<typeof __getContext_database>) => {
    const __instance = __registry_database.get(__context);
    if (__instance === undefined) return undefined;
    __registry_database.delete(__context);
    const __cleanup: unknown = Reflect.apply((async (instance) => instance.close()), undefined, [__instance, __context]);
    if (__cleanup && typeof (__cleanup as PromiseLike<void>).then === "function") {
      return Promise.resolve(__cleanup).then(() => __instance);
    }
    return __instance;
  },
};
const __proxy_database = new Proxy({} as ReturnType<typeof __createScoped_database>, {
  get(_target, __property) {
    const __instance = __resolveScoped_database();
    const __value: unknown = Reflect.get(__instance, __property, __instance);
    return typeof __value === "function" ? __value.bind(__instance) : __value;
  },
  set(_target, __property, __value: unknown) {
    const __instance = __resolveScoped_database();
    return Reflect.set(__instance, __property, __value, __instance);
  },
  deleteProperty(_target, __property) {
    return Reflect.deleteProperty(__resolveScoped_database(), __property);
  },
  has(_target, __property) {
    return Reflect.has(__resolveScoped_database(), __property);
  },
  getPrototypeOf() {
    return Reflect.getPrototypeOf(__resolveScoped_database());
  },
  ownKeys() {
    return Reflect.ownKeys(__resolveScoped_database());
  },
  getOwnPropertyDescriptor(_target, __property) {
    const __descriptor = Reflect.getOwnPropertyDescriptor(__resolveScoped_database(), __property);
    return __descriptor ? { ...__descriptor, configurable: true } : undefined;
  },
}) as ReturnType<typeof __createScoped_database>;
export const [database, databaseScope] = [__proxy_database, __controller_database] as const;
