// Generated by Compdi
// Style: interfaces only for scoped contracts, explicit generics on defineScoped with context key type
interface IRequestContext {
  traceId: string;
}

interface ISessionStore {
  get(key: string): unknown;
}

class Config {
  constructor(readonly env: string) {}
}

class Logger {
  constructor(readonly config: Config) {}
  log(msg: string) { console.log(msg); }
}

class RequestContext implements IRequestContext {
  constructor(readonly config: Config, readonly logger: Logger, readonly traceId: string) {}
}

class SessionStore implements ISessionStore {
  constructor(readonly config: Config) {}
  get(key: string) { return key; }
}

export const config = new Config("production");
export const logger = new Logger(config);

interface RequestCtx { requestId: string; }
interface SessionCtx { sessionId: string; }

const __registry_getRequestContext = new Map<RequestCtx, IRequestContext>();
const __getScoped_getRequestContext = (__ctx: RequestCtx) => {
  if (__registry_getRequestContext.has(__ctx)) return __registry_getRequestContext.get(__ctx)!;
  const __val = new RequestContext(config, logger, "trace-001");
  __registry_getRequestContext.set(__ctx, __val);
  return __val;
};
__getScoped_getRequestContext.has = (__ctx: RequestCtx) => __registry_getRequestContext.has(__ctx);
__getScoped_getRequestContext.peek = (__ctx: RequestCtx) => __registry_getRequestContext.get(__ctx);
__getScoped_getRequestContext.release = (__ctx: RequestCtx) => {
  const __val = __registry_getRequestContext.get(__ctx);
  __registry_getRequestContext.delete(__ctx);
  return __val;
};
export const getRequestContext = __getScoped_getRequestContext;
const __registry_getSession = new Map<SessionCtx, ISessionStore>();
const __getScoped_getSession = (__ctx: SessionCtx) => {
  if (__registry_getSession.has(__ctx)) return __registry_getSession.get(__ctx)!;
  const __val = new SessionStore(config);
  __registry_getSession.set(__ctx, __val);
  return __val;
};
__getScoped_getSession.has = (__ctx: SessionCtx) => __registry_getSession.has(__ctx);
__getScoped_getSession.peek = (__ctx: SessionCtx) => __registry_getSession.get(__ctx);
__getScoped_getSession.release = (__ctx: SessionCtx) => {
  const __val = __registry_getSession.get(__ctx);
  __registry_getSession.delete(__ctx);
  return __val;
};
export const getSession = __getScoped_getSession;

export const session: ISessionStore = getSession({ sessionId: "abc" });