import MagicString from "magic-string";
import { collectBindings, parseWithOxc } from "./context";
import { collectImportReplacements } from "./imports";
import { collectSingletonReplacements } from "./singletons";
import { collectScopedReplacements } from "./scoped";
import { collectTeardownReplacements } from "./teardown";
import { collectTransientReplacements } from "./transient";

export type TransformCompdiMacrosResult = {
  code: string;
  map: ReturnType<MagicString["generateMap"]>;
};

export function transformCompdiMacros(
  code: string,
  id: string
): TransformCompdiMacrosResult | null {
  if (!/\.[cm]?[jt]sx?$/.test(id)) {
    return null;
  }

  if (
    !code.includes("@compdi/core") &&
    !code.includes('"compdi/macros"') &&
    !code.includes("'compdi/macros'") &&
    !code.includes('"compdi"') &&
    !code.includes("'compdi'")
  ) {
    return null;
  }

  if (!parseWithOxc(code, id)) {
    return null;
  }

  const ms = new MagicString(code);
  const bindings = collectBindings(code);

  const hasSingletons  = collectSingletonReplacements(code, bindings, ms);
  const hasTransients  = collectTransientReplacements(code, bindings, ms);
  const hasTeardowns   = collectTeardownReplacements(code, bindings, ms);
  const hasScoped      = collectScopedReplacements(code, bindings, ms);

  if (!hasSingletons && !hasTransients && !hasTeardowns && !hasScoped) {
    return null;
  }

  // Only erase the import when there are actual macro calls to replace.
  // Without this guard, barrel re-export files (e.g. compdi/macros dist) would
  // have their import erased, leaving dangling export references.
  collectImportReplacements(code, ms);

  ms.prepend("// Generated by Compdi\n");

  return {
    code: ms.toString(),
    map: ms.generateMap({ hires: true, source: id, includeContent: true })
  };
}


