import MagicString from "magic-string";
import { collectBindings, parseWithOxc } from "./context";
import { collectAsyncSingletonReplacements } from "./async";
import { collectImportReplacements } from "./imports";
import { collectLazyReplacements } from "./lazy";
import { collectSingletonReplacements } from "./singletons";
import { collectScopedReplacements } from "./scoped";
import { collectTeardownReplacements } from "./teardown";
import { collectTransientReplacements } from "./transient";
import type { Replacement } from "./types";

export type TransformCompdiMacrosResult = {
  code: string;
  map: ReturnType<MagicString["generateMap"]>;
};

function applyReplacements(
  code: string,
  id: string,
  replacements: Replacement[]
): TransformCompdiMacrosResult {
  if (replacements.length === 0) {
    const ms = new MagicString(code);

    return {
      code,
      map: ms.generateMap({ hires: true, source: id, includeContent: true })
    };
  }

  const ms = new MagicString(code);

  const sorted = [...replacements].sort((left, right) => right.start - left.start);

  for (const replacement of sorted) {
    ms.overwrite(replacement.start, replacement.end, replacement.code);
  }

  ms.prepend("// Generated by Compdi\n");

  return {
    code: ms.toString(),
    map: ms.generateMap({ hires: true, source: id, includeContent: true })
  };
}

export function transformCompdiMacros(
  code: string,
  id: string
): TransformCompdiMacrosResult | null {
  if (!/\.[cm]?[jt]sx?$/.test(id)) {
    return null;
  }

  if (
    !code.includes("@compdi/core") &&
    !code.includes('"compdi/macros"') &&
    !code.includes("'compdi/macros'") &&
    !code.includes('"compdi"') &&
    !code.includes("'compdi'")
  ) {
    return null;
  }

  if (!parseWithOxc(code, id)) {
    return null;
  }

  const bindings = collectBindings(code);
  const macroReplacements: Replacement[] = [
    ...collectSingletonReplacements(code, bindings),
    ...collectTransientReplacements(code, bindings),
    ...collectLazyReplacements(code, bindings),
    ...collectTeardownReplacements(code, bindings),
    ...collectAsyncSingletonReplacements(code, bindings, "create"),
    ...collectAsyncSingletonReplacements(code, bindings, "define"),
    ...collectScopedReplacements(code, bindings)
  ];

  // Only erase the import when there are actual macro calls to replace.
  // Without this guard, barrel re-export files (e.g. compdi/macros dist) would
  // have their import erased, leaving dangling export references.
  const replacements: Replacement[] = macroReplacements.length > 0
    ? [...collectImportReplacements(code), ...macroReplacements]
    : macroReplacements;

  if (replacements.length === 0) {
    return null;
  }

  return applyReplacements(code, id, replacements);
}

