import MagicString from "magic-string";
import { collectBindings, parseWithOxc } from "./context";
import { collectAsyncSingletonReplacements } from "./async";
import { collectImportReplacements } from "./imports";
import { collectLazyReplacements } from "./lazy";
import { collectSingletonReplacements } from "./singletons";
import { collectTeardownReplacements } from "./teardown";
import { collectTransientReplacements } from "./transient";
import type { Replacement } from "./types";

export type TransformCompdiMacrosResult = {
  code: string;
  map: ReturnType<MagicString["generateMap"]>;
};

function applyReplacements(
  code: string,
  id: string,
  replacements: Replacement[]
): TransformCompdiMacrosResult {
  if (replacements.length === 0) {
    const ms = new MagicString(code);

    return {
      code,
      map: ms.generateMap({ hires: true, source: id, includeContent: true })
    };
  }

  const ms = new MagicString(code);
  const sorted = [...replacements].sort((left, right) => right.start - left.start);

  for (const replacement of sorted) {
    ms.overwrite(replacement.start, replacement.end, replacement.code);
  }

  ms.prepend("// Generated by Compdi\n");

  return {
    code: ms.toString(),
    map: ms.generateMap({ hires: true, source: id, includeContent: true })
  };
}

export function transformCompdiMacros(
  code: string,
  id: string
): TransformCompdiMacrosResult | null {
  if (!/\.[cm]?[jt]sx?$/.test(id)) {
    return null;
  }

  if (!code.includes("@compdi/core") && !code.includes('"compdi"') && !code.includes("'compdi'")) {
    return null;
  }

  if (!parseWithOxc(code, id)) {
    return null;
  }

  const bindings = collectBindings(code);
  const replacements: Replacement[] = [
    ...collectImportReplacements(code),
    ...collectSingletonReplacements(code, bindings),
    ...collectTransientReplacements(code, bindings),
    ...collectLazyReplacements(code, bindings),
    ...collectTeardownReplacements(code, bindings),
    ...collectAsyncSingletonReplacements(code, bindings, "create"),
    ...collectAsyncSingletonReplacements(code, bindings, "define")
  ];

  if (replacements.length === 0) {
    return null;
  }

  return applyReplacements(code, id, replacements);
}
