// Generated by Compdi
// Style: plain classes, explicit generic only on createTransient
class Config {
  constructor(readonly env: string) {}
}

class Logger {
  constructor(readonly config: Config) {}
  log(msg: string) { console.log(msg); }
}

class RequestHandler {
  constructor(
    readonly config: Config,
    readonly logger: Logger,
    readonly requestId: string
  ) {}
  handle() { this.logger.log(this.requestId); }
}

export const config = new Config("production");
export const logger = new Logger(config);
export const handler = new RequestHandler(config, logger, "req-001");
