// Generated by Compdi
// Style: interfaces only on handler types, no generics at all (fully inferred)
interface IRequestHandler {
  handle(): void;
}

interface IAuditHandler {
  audit(action: string): void;
}

class Config {
  constructor(readonly env: string) {}
}

class Logger {
  constructor(readonly config: Config) {}
  log(msg: string) { console.log(msg); }
}

class RequestHandler implements IRequestHandler {
  constructor(readonly config: Config, readonly logger: Logger) {}
  handle() { this.logger.log("handled"); }
}

class AuditHandler implements IAuditHandler {
  constructor(readonly config: Config, readonly logger: Logger) {}
  audit(action: string) { this.logger.log(action); }
}

export const config = new Config("production");
export const logger = new Logger(config);
export const createRequestHandler = () => new RequestHandler(config, logger);
export const createAuditHandler = () => new AuditHandler(config, logger);
